Do Iter13 (add retries)
talx-hub/malerter pull request #19
Opened 2024-12-06 01:00 UTC by talx-hub

2024-12-06 01:07 UTC, talx-hub commented
Приветы! да, часть проверок не прошла.. но это я себе усложнял задачу, добавив дополнительные проверки. Все исправлю в 4м спринте! и тестами покрою и линтеры перестанут ругаться!
надеюсь -- главное, что прошли автотесты практикума))

2024-12-06 15:09 UTC, edylcrm requested changes

2024-12-06 15:09 UTC, edylcrm commented on cmd/server/main.go
> +	} else {
Можно без else

2024-12-06 15:09 UTC, edylcrm commented on internal/api/handlers.go
> +func fromJSON(body io.Reader) (model.Metric, error) {
Не нравится мне чего-то вот этот io.Reader как параметр и название fromJSON

2024-12-06 15:09 UTC, edylcrm commented on internal/api/handlers.go
> +func fromJSONs(body io.Reader) ([]model.Metric, error) {
И вот это тоже

2024-12-06 15:09 UTC, edylcrm commented on internal/api/handlers.go
> +	metrics, err := fromJSONs(r.Body)
Но в целом если абстракция для такого, то может быть и норм, но я бы так не писал

2024-12-06 15:09 UTC, edylcrm commented on internal/api/handlers.go
> +	if err = h.service.Batch(context.Background(), metrics); err != nil {
context нужно доставать из request

2024-12-06 15:09 UTC, edylcrm commented on internal/api/handlers.go
> +			if err = h.service.Batch(context.Background(), metrics); err != nil {
Тоже самое про context

2024-12-06 15:09 UTC, edylcrm commented on internal/api/handlers.go
> +		if errors.As(err, &pgErr) && pgerrcode.IsConnectionException(pgErr.Code) {
Опять же retry на уровне handlers не очень нравится. Может такое выносить в работу с БД?

2024-12-06 15:09 UTC, edylcrm commented on internal/api/handlers.go
> +		} else {
Можно без else

2024-12-06 15:09 UTC, edylcrm commented on internal/api/handlers.go
> +	if err = h.service.Add(context.Background(), metric); err != nil {
Про context тоже самое

2024-12-06 15:09 UTC, edylcrm commented on internal/api/handlers.go
> +			err = retry(context.Background(), 0, h, w)
И здесь про context

2024-12-06 15:09 UTC, edylcrm commented on internal/api/handlers.go
> +			if err = h.service.Add(context.Background(), metric); err != nil {
И здесь про context

2024-12-06 15:09 UTC, edylcrm commented on internal/api/handlers.go
> +		} else {
Можно без else. Вообще много вложенностей if else if err != nil

2024-12-06 15:09 UTC, edylcrm commented on internal/api/handlers.go
> +			err = retry(context.Background(), 0, h, w)
Про context тоже самое

2024-12-06 15:09 UTC, edylcrm commented on internal/api/handlers.go
> +			metric, err = h.service.Find(context.Background(), dummyKey)
Про context тоже самое

2024-12-06 15:09 UTC, edylcrm commented on internal/api/handlers.go
> +	err = h.service.Add(context.Background(), metric)
Про context тоже самое

2024-12-06 15:09 UTC, edylcrm commented on internal/api/handlers.go
> +			err = h.service.Add(context.Background(), metric)
Про context тоже самое

2024-12-06 15:09 UTC, edylcrm commented on internal/api/handlers.go
> +	m, err := h.service.Find(context.Background(), dummyKey)
Про context тоже самое

2024-12-06 15:09 UTC, edylcrm commented on internal/api/handlers.go
> +			err = retry(context.Background(), 0, h, w)
Про context тоже самое

2024-12-06 15:09 UTC, edylcrm commented on internal/api/handlers.go
> +			m, err = h.service.Find(context.Background(), dummyKey)
Про context тоже самое

2024-12-06 15:09 UTC, edylcrm commented on internal/api/handlers.go
> +	metric, err = h.service.Find(context.Background(), dummyKey)
Про context тоже самое

2024-12-06 15:09 UTC, edylcrm commented on internal/api/handlers.go
> +			err = retry(context.Background(), 0, h, w)
Про context тоже самое

2024-12-06 15:09 UTC, edylcrm commented on internal/api/handlers.go
> +			metric, err = h.service.Find(context.Background(), dummyKey)
Про context тоже самое

2024-12-06 15:09 UTC, edylcrm commented on internal/api/handlers.go
> +	metrics, err := h.service.Get(context.Background())
Про context тоже самое

2024-12-06 15:09 UTC, edylcrm commented on internal/api/handlers.go
> +			metrics, err = h.service.Get(context.Background())
Про context тоже самое

2024-12-06 15:09 UTC, edylcrm commented on internal/api/handlers.go
> +	err := h.service.Ping(context.Background())
Про context тоже самое. Вообще везде можно поправить

2024-12-06 15:09 UTC, edylcrm commented on internal/api/handlers.go
> +	err := h.service.Ping(ctx)
Точно нужен ping на каждый retry? Обычно есть что-то вроде health check где как раз и проверяется этот ping. На остальные запросы не нужно этого делать
https://habr.com/ru/companies/otus/articles/676342/ - вот здесь написано

2024-12-06 15:09 UTC, edylcrm commented on internal/repository/db/db.go
> +	for _, m := range batch {
defer tx.Rollback() если по какой-то причине произошла ошибка

2024-12-10 13:31 UTC, talx-hub commented on cmd/server/main.go
> +	} else {
что-то тут не получается без else(
если его уберу -- то даже когда БД не инициализирована, будет создаваться defer и storag`y присваиваться датабаза

2024-12-10 19:24 UTC, talx-hub commented on internal/repository/db/db.go
> +	defer func() {
теперь, конечно, при каждом успешном пуше батча здесь в лог пишется ошибка..

2024-12-10 19:27 UTC, talx-hub commented on internal/repository/db/db.go
> +func WithConnectionCheck(dbMethod Method) (any, error) {
изменил реализацию повтора запроса к БД на вот такое. Получилось вроде красиво -- оберточка над методами БД. но чтот много всяких any...

2024-12-10 19:28 UTC, talx-hub commented on internal/repository/db/db.go
> +	for _, m := range batch {
добавил defer

2024-12-10 19:29 UTC, talx-hub commented on internal/api/handlers.go
> +	err := h.service.Ping(ctx)
убрал ping, переделал реализацию retry -- сделал retry обобщенной функцией. Перенес реализацию в пакет в БД

2024-12-10 19:29 UTC, talx-hub commented on internal/api/handlers.go
> +	err := h.service.Ping(context.Background())
везде поправил context

2024-12-10 19:30 UTC, talx-hub commented on internal/api/handlers.go
> +	metrics, err := fromJSONs(r.Body)
переименовал на extractJSONs

2024-12-10 19:30 UTC, talx-hub commented on internal/api/handlers.go
> +func fromJSONs(body io.Reader) ([]model.Metric, error) {
переименовал на extractJSONs

2024-12-10 19:30 UTC, talx-hub commented on internal/api/handlers.go
> +func fromJSON(body io.Reader) (model.Metric, error) {
переименовал на extractJSON

2024-12-10 19:32 UTC, talx-hub commented on internal/api/handlers.go
> +		if errors.As(err, &pgErr) && pgerrcode.IsConnectionException(pgErr.Code) {
вынес retry в пакет с БД

2024-12-11 06:37 UTC, talx-hub commented on internal/service/server/metricsdumper.go
>  package server
просчитался.. но где?? в результате рефакторинга этот файл вообще схлопнулся в пустую прослойку.. это норм?

2024-12-11 07:22 UTC, edylcrm approved these changes

2024-12-11 08:40 UTC, merged